name: Demo Job
run-name: This action has been run

on: [push]

jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      
      - name: Checkout
        uses: actions/checkout@v6.0.0

      - name: Build DotNet
        uses: Elskom/build-dotnet@v1.1.1

      - name: Run tests
        uses: EasyDesk/action-dotnet-test@v1.0.0

      - name: dotnet-format
        uses: xt0rted/dotnet-format@v1.2.0
        with:
          repo-token: ${{ github.token }}
          version: 3
          action: check
          fail-fast: false
